#164233525 View Profile
andela/titan-dev-ah-frontend pull request #13
Opened 2019-03-13 10:15 UTC by YvesIraguha

#### What does this PR do?
- It creates `view profile and bookmarked articles` with HTML/CSS
#### Description of Task to be completed?
-  Create `html/css` pages of view profile.
- Enable responsiveness 
- Create `Latest and bookmarked articles` view. 
#### How should this be manually tested?
* Fetch origin
* Checkout the branch `ft-view-profile-page-164233525`
* Go to ```pages/profile.html``` page
* Click on `Latest or Bookmarks` to view different articles. 
* And use the inspector to view the page with different devices.
#### Any background context you want to provide?
Since we have to keep consistency, the navigation bar is not included on the mobile view as supposed to be, It will be added from the landing page, instead of building another one. 
#### What are the relevant pivotal tracker stories?
#164233525
<img width="600" alt="Screen Shot 2019-03-13 at 12 05 01" src="https://user-images.githubusercontent.com/34691070/54270540-4bbc2100-4588-11e9-8c01-0a0b2660640f.png">
<img width="364" alt="Screen Shot 2019-03-13 at 12 06 25" src="https://user-images.githubusercontent.com/34691070/54270609-74441b00-4588-11e9-9df0-7d3362977e3d.png">
<img width="251" alt="Screen Shot 2019-03-13 at 12 13 57" src="https://user-images.githubusercontent.com/34691070/54271113-8d999700-4589-11e9-9a55-8357406fdbb4.png">

2019-03-14 07:08 UTC, abayo-luc requested changes
- Well done on responsiveness Mr. @YvesIraguha 
- Your CSS and HTML look neat (`status:  200`)
- What do you think about aligning the social icons horizontally, since vertical alignment is leaving large empty space?
- I have noticed a slight difference between the left and right margin/padding on profile page.

2019-03-14 14:00 UTC, espoirMur requested changes
Bro, can you  check the margin between the single article card and the title?

2019-03-14 14:44 UTC, abayo-luc commented
<img width="382" alt="Screen Shot 2019-03-14 at 16 39 33" src="https://user-images.githubusercontent.com/20681465/54365850-4d651200-4678-11e9-9665-e7d404551d00.png">
<img width="342" alt="Screen Shot 2019-03-14 at 16 42 34" src="https://user-images.githubusercontent.com/20681465/54365855-50f89900-4678-11e9-9903-d75fc9535b54.png">
- The codent inside the card need little bit of padding 
- The card is too sequized with tabgs

2019-03-14 15:24 UTC, espoirMur approved these changes

2019-03-15 08:33 UTC, abayo-luc approved these changes

2019-03-15 11:20 UTC, merged