#163518636 Setup Redux
andela/titan-dev-ah-frontend pull request #24
Opened 2019-04-02 15:02 UTC by YvesIraguha

#### What does this PR do?
- Setup redux 
#### Description of Task to be completed?
- Include redux in the application
- Connect react with redux 
- Create dummy actionCreator, store, and reducer 
- Ensure that dummy actionCreator, store, and reducer is working
#### How should this be manually tested?
- Fork the repo and checkout 
#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
#### Screenshots (if appropriate)
#### Questions:

2019-04-03 15:28 UTC, espoirMur approved these changes
LGTM

2019-04-04 07:35 UTC, abayo-luc approved these changes

2019-04-04 09:42 UTC, puritybirir requested changes
Additional changes:

- Change
- Ensure all styles are in our CSS files and not internal.

 the views folder to  components

2019-04-04 09:42 UTC, puritybirir commented on src/views/Home.js
> +        <h4>{el.title}</h4>
Better Variable Naming. What does el represent?

2019-04-04 09:42 UTC, puritybirir commented on src/views/Article.js
> +          style={{
Why do we have internal styling

2019-04-04 09:42 UTC, puritybirir commented on src/views/Home.js
> +        style={{ borderBottom: '1px solid red', width: '700px' }}
Internal styles

2019-04-04 09:42 UTC, puritybirir commented on src/views/Home.js
> +import React, { Component } from 'react';
Component is imported but not used

2019-04-05 07:53 UTC, puritybirir approved these changes

2019-04-09 08:36 UTC, puritybirir approved these changes

2019-04-09 08:36 UTC, merged