#165054398 Setup Eslint
andela/titan-dev-ah-frontend pull request #31
Opened 2019-04-04 14:20 UTC by YvesIraguha

#### What does this PR do?
- Enable eslint for linting. 
#### Description of Task to be completed?
- Enable eslint 
- Enable HoundCI
#### What are the relevant pivotal tracker stories?
#165054398

2019-04-04 14:23 UTC, abayo-luc approved these changes

2019-04-04 14:25 UTC, niomwungeri-fabrice approved these changes

2019-04-05 07:48 UTC, puritybirir requested changes
I would like a couple of rules added:

2019-04-05 07:48 UTC, puritybirir commented on .vscode/launch.json
> +{
Vscode files should not be commited

2019-04-05 07:48 UTC, puritybirir commented on .vscode/settings.json
> +  "editor.formatOnSave": true,
Vscode files should be ignored

2019-04-05 07:48 UTC, puritybirir commented on .eslintrc.json
> +  "extends": ["eslint:recommended", "plugin:react/recommended", "airbnb"],
In this line,

` "extends": ["eslint:recommended", "plugin:react/recommended", "airbnb"],`

change to  `"extends": [ "airbnb", "plugin:prettier/recommended", "prettier/react"],`

2019-04-05 07:48 UTC, puritybirir commented on .eslintrc.json
> +  "rules": {
Under rules also add 

`{
        "newlines-between": "always"
      }`

2019-04-05 12:12 UTC, puritybirir approved these changes

2019-04-05 12:12 UTC, merged