#163518645 Social Auth
andela/titan-dev-ah-frontend pull request #35
Opened 2019-04-12 15:09 UTC by abayo-luc

#### What does this PR do?
Add social auth
#### Description of Task to be completed?
- Activated social login button
- A user can log in with Google, Facebook, or Twitter
#### How should this be manually tested?
- clone the repo and check out the following branch `ft-social-auth-163518645 `
- run `yarn start` and navigate to /login in your browser
- Try one of the social auth buttons
### Story ID
#163518645

2019-04-18 08:32 UTC, Musigwa-zz requested changes
Good work @abayo-luc, please consider the comments I left on some of the files changes.

2019-04-18 08:32 UTC, Musigwa commented on .eslintrc.json
> +    "react/forbid-prop-types": "off",
@abayo-luc, is there a meaningful reason why you disabled this rule?

2019-04-18 08:32 UTC, Musigwa commented on .eslintrc.json
> +    "jsx-a11y/click-events-have-key-events": "off",
@abayo-luc, do you mind checking out this [reason](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/click-events-have-key-events.md) why we should use this rule?

2019-04-23 08:00 UTC, Musigwa-zz approved these changes

2019-04-23 08:53 UTC, niomwungeri-fabrice approved these changes
Good Job mate!

2019-04-25 12:38 UTC, puritybirir approved these changes

2019-04-25 12:38 UTC, merged