Ft create article 163518647
andela/titan-dev-ah-frontend pull request #38
Opened 2019-04-15 14:22 UTC by YvesIraguha

#### What does this PR do?
- Integrate the interface for creating an article with react 
- Enable article cration 
#### Description of Task to be completed?
_ Create tests
- Connect the component with redux
- Create some articles to test the functionality. 
#### How should this be manually tested?
- Clone the repos 
- Check out the branch `ft-create-article-163518647`
- Install all dependencies by `yarn install`
- Start the server using `yarn start`
- Start the server for the backend project
- Login to the backend server using client tool like the postman
- Get the token, and store it in localStorage using `localStorage.setItem('token',value);
- Check your browser, where the application was opened
- Create an article. 
#### Any background context you want to provide?
Some of the fields that were developed in mockups were ignored since there is no backend functionality for them. Moreover, the text editor has been changed due to the adjustments issues the original one had. For reference, attached are images of mockup and real react application. 
#### What are the relevant pivotal tracker stories?
#163518647
#### Screenshots (if appropriate)

#### Questions:

2019-04-17 20:54 UTC, abayo-luc requested changes
Overall you did a great job Mr. @YvesIraguha . Very nice and clean syntax. Just, take a look at the comment I left, and let me know how you feel about them. N.B: Ping me when you are done!

2019-04-17 20:54 UTC, abayo-luc commented on src/.env
> +CLOUD_NAME="dtzujn9pi"
Why this file is in git?

2019-04-17 20:54 UTC, abayo-luc commented on src/components/common/Buttons/confirm.js
> +import React from "react";
this button was changed to BasicButton, please rebase and update the changes.

2019-04-17 20:54 UTC, abayo-luc commented on src/components/common/editor/editorConfig.js
> +export const toolbarConfig = {
since this is not a component, move them into ```utils``` or ```config```

2019-04-17 20:54 UTC, abayo-luc commented on src/redux/actionTypes.js
> +export const NEW_ARTICLE = "NEW_ARTICLE";
consider adding jsDoc comments for easy readability.

2019-04-17 20:54 UTC, abayo-luc commented on src/redux/actions/newArticle.js
> +        headers: {
we can add this token to the created axios instance, under utils.

2019-04-17 20:54 UTC, abayo-luc commented on src/styles/pages/_new-article.scss
> +    // .button--white {
If these are doing nothing, you can remove them.

2019-04-17 20:54 UTC, abayo-luc commented on src/views/NewArticle.js
> +    this.submitArticle = this.submitArticle.bind(this);
User arrow functions and you will not need to bind all these properties to ```this``` context

2019-04-17 20:54 UTC, abayo-luc commented on src/views/NewArticle.js
> +    if (!title || title.length < 10) {
consider moving all validation into their own file under utils. We should keep our component as minimal as possible.

2019-04-17 20:54 UTC, abayo-luc commented on src/views/NewArticle.js
> +    if (event.keyCode === 13 && tag.length) {
Very nice Mr. @YvesIraguha

2019-04-17 20:54 UTC, abayo-luc commented on src/views/NewArticle.js
> +  article: PropTypes.shape({
Nice approach!

2019-04-17 20:54 UTC, abayo-luc commented on src/views/Not-Found.js
> +import React from "react";
Consider renaming this file respecting JavaScript standards (camel care or Pascal case) => NotFound.js

2019-04-17 20:54 UTC, abayo-luc commented on yarn.lock
>      "@babel/plugin-transform-react-jsx-self" "^7.0.0"
Remove yarn.lock from git

2019-04-18 09:29 UTC, abayo-luc requested changes
Use arrow functions which do not require to bind them to this context. Also, Fabrice created flash messages, you can use them to indicate whether an article was created successfully or not.

2019-04-18 09:29 UTC, abayo-luc commented on src/views/NewArticle.js
> +    const { name } = event.target;
```const {name, value} = event.target```

2019-04-18 09:29 UTC, abayo-luc commented on src/views/NewArticle.js
> +    const { article } = this.props;
```const {article, createArticle} = this.props```

2019-04-18 09:29 UTC, abayo-luc commented on src/views/NewArticle.js
> +    const { onInputChange } = this.props;
then remove this

2019-04-18 09:29 UTC, abayo-luc commented on src/views/NewArticle.js
> +    const { createArticle } = this.props;
then remove this

2019-04-23 12:12 UTC, abayo-luc approved these changes

2019-04-23 12:39 UTC, niomwungeri-fabrice requested changes

2019-04-23 12:39 UTC, niomwungeri-fabrice commented on src/__tests__/__actions__/article.test.js
> +const BASE_URL = "http://localhost:3000/api/v1";
What do you think if you have this in process.env? @YvesIraguha

2019-04-23 12:39 UTC, niomwungeri-fabrice commented on src/components/common/Buttons/confirm.js
> +
If I remember well, we have decided to get rid of this button @YvesIraguha

2019-04-23 12:39 UTC, niomwungeri-fabrice commented on src/styles/pages/_new-article.scss
> +      // }
Is it possible to remove comments? @YvesIraguha

2019-04-23 12:58 UTC, niomwungeri-fabrice approved these changes

2019-04-26 01:41 UTC, puritybirir approved these changes

2019-04-26 01:41 UTC, merged