#64215717 Reset Password Page
andela/titan-dev-ah-frontend pull request #4
Opened 2019-03-06 15:36 UTC by YvesIraguha

#### What does this PR do?
Add a reset password page
#### Description of Task to be completed?
• Create a reset password page and make it responsive
#### How should this be manually tested?
* Fetch origin
* Checkout the branch `ft-reset-password-page-64215717 `
* Open ```reset-password.html```
* And use the inspector to view the page with different devices.
### Background history
For sake of consistency in the project: Some of the heights in the design were adjusted to make sure that it meets the consistency, for instance, the height of input or button in the design might not be exactly the same as the height in HTML page. 
#### What are the relevant pivotal tracker stories?
64215717

Design 
<img width="1440" alt="screen shot 2019-03-06 at 17 29 34" src="https://user-images.githubusercontent.com/34691070/53892732-8593a180-4035-11e9-9d2e-cfee538525dd.png">
<img width="1026" alt="screen shot 2019-03-06 at 17 30 58" src="https://user-images.githubusercontent.com/34691070/53892814-b07df580-4035-11e9-8a3c-52f9d08856d9.png">
<img width="326" alt="screen shot 2019-03-06 at 17 32 02" src="https://user-images.githubusercontent.com/34691070/53892881-cab7d380-4035-11e9-808f-7c6150b909eb.png">

2019-03-07 07:39 UTC, abayo-luc requested changes
- The rest password card should be in the center
- Consider to use percentage for margin and paddling instead of px 
- In terms of font-size and font-family, use the variables for sake of constancy and matainability. 
- Well done Mr. yves. The responsiviness is OK!

2019-03-07 07:39 UTC, abayo-luc commented on pages/reset-password.html
> +          <p>Don't have an account? <a>sign up now!</a></p>
git the indicate ```href``` in your Sign up link.

2019-03-07 07:39 UTC, abayo-luc commented on pages/reset-password.html
> +              <input type="submit" value="submit" class="btn" />
the background color of this button is not consistent across all device view.

2019-03-07 07:39 UTC, abayo-luc commented on sass/pages/_reset-password.scss
> +        font-size: 14px;
you can create a variable for font-size so that everyone will keep the same font-size.

2019-03-07 07:39 UTC, abayo-luc commented on sass/pages/_reset-password.scss
> +        font-size: 24px;
user variables

2019-03-07 11:25 UTC, espoirMur reviewed
Nice job big bro, 
Especially on the responsiveness, 
What do you think about the space between the log and the top of the page on mobile view?

2019-03-07 11:27 UTC, espoirMur reviewed
Why have you removed all the content in this file?

2019-03-07 12:45 UTC, YvesIraguha commented
> Why have you removed all the content in this file?

If you check very well, the content removed was the content related to `npm, yarn, overage` and other backend tasks, and I don't think we need them for this `html/css` repository.

2019-03-07 12:51 UTC, abayo-luc approved these changes

2019-03-08 05:53 UTC, puritybirir commented
The File is still not fully responsive

2019-03-08 10:35 UTC, espoirMur approved these changes
Look good to me bro...

2019-03-08 10:47 UTC, merged