#165352853  Read Article
andela/titan-dev-ah-frontend pull request #41
Opened 2019-04-17 16:23 UTC by YvesIraguha

#### What does this PR do?
- Read article 
#### Description of Task to be completed?
- Fetch the article from a database 
- Transform article body into html 
- Retrieve  articles that exist to the right side of a single article
#### How should this be manually tested?
- Clone the repository and check out the branch `ft-read article-165352853`
- Run `yarn` to install all dependencies
- Run `yarn test` to run all tests 
- Start your backend server 
- Create an article using postman client tool by consuming `POST: {backEndUrl}/api/v1/articles`
- Get the `slug` of the article created
- Start the front-end server by running `yarn start`
- Navigate to `localhost:8080/articles/slug`
- You should see the article you created, with other articles in your database on the right side of the main article. 

#### What are the relevant pivotal tracker stories?
#165352853

2019-04-23 08:06 UTC, abayo-luc requested changes
Fix hound CI issues.

2019-04-25 16:00 UTC, abayo-luc requested changes
Well done Mr. @YvesIraguha , please check on some feedback I left and let me know when you are done applying them.

2019-04-25 16:00 UTC, abayo-luc commented on src/__tests__/__actions__/articleActionCreator.test.js
> +const BASE_URL = "http://localhost:3000/api/v1";
Move this to .env, as we are not sure of the port everyone will be running their backend.

2019-04-25 16:00 UTC, abayo-luc commented on src/__tests__/__views__/ReadArticle.test.js
> +import "babel-polyfill";
What does this doing here? also, we are using babel-7, which use @babel/polyiff not that one.

2019-04-25 16:00 UTC, abayo-luc commented on src/redux/reducers/articleReducers.js
> +const initialState = { isFetching: true, asideArticles: { articles: [] } };
on sideArticles, use object instead of array. By using object with keys, it become easier to update the state without mutating it. https://redux.js.org/recipes/structuring-reducers/immutable-update-patterns

2019-04-25 16:00 UTC, abayo-luc commented on src/redux/reducers/index.js
> +import { articleReducer } from "./articleReducers";
can you use default import for the sake of consistency?

2019-04-25 16:00 UTC, abayo-luc commented on src/utils/axios.js
>  export default axios.create({
consider moving all these to .env, since API_BASE_URL will vary based on the environment.

2019-04-25 16:00 UTC, abayo-luc commented on src/utils/helpers/calculateTimeStamp.js
> +export default time => {
There is a simple method which can the job effectively, ```time.toDateString()```

2019-04-29 12:03 UTC, abayo-luc approved these changes

2019-04-29 13:41 UTC, niomwungeri-fabrice approved these changes

2019-04-29 18:41 UTC, oesukam requested changes

2019-04-29 18:41 UTC, oesukam commented on src/__tests__/__actions__/readArticleAction.test.js
> +dotenv.config();
@YvesIraguha This should be configured globally to avoid importing it in every file

2019-04-29 18:41 UTC, oesukam commented on src/__tests__/__actions__/readArticleAction.test.js
> +  });
@YvesIraguha New empty line required after line 37.

2019-04-29 18:41 UTC, oesukam commented on src/__tests__/__actions__/readArticleAction.test.js
> +  });
@YvesIraguha New empty line required

2019-04-29 18:41 UTC, oesukam commented on src/__tests__/__actions__/readArticleAction.test.js
> +  });
@YvesIraguha Empty line required.

2019-04-29 18:41 UTC, oesukam commented on src/__tests__/__actions__/readArticleAction.test.js
> +  });
@YvesIraguha Empty line required.

2019-04-29 18:41 UTC, oesukam commented on src/__tests__/__components__/Cards/mainCard.test.js
> +  });
Empty line required.

2019-04-29 18:41 UTC, oesukam commented on src/__tests__/__components__/Cards/mainCard.test.js
> +    expect(wrapper.find(".left")).toHaveLength(1);
Empty line required.

2019-04-29 18:41 UTC, oesukam commented on src/__tests__/__reducers__/readArticle.test.js
> +  });
Empty line required.

2019-04-29 18:41 UTC, oesukam commented on src/__tests__/__reducers__/readArticle.test.js
> +  });
Empty line required.

2019-04-29 18:41 UTC, oesukam commented on src/__tests__/__reducers__/readArticle.test.js
> +  });
Empty line required.

2019-04-29 18:41 UTC, oesukam commented on src/__tests__/__utils__/helperFunctions.test.js
> +  });
Empty line required.

2019-04-29 18:41 UTC, oesukam commented on src/__tests__/__utils__/helperFunctions.test.js
> +  });
Empty line required.

2019-04-29 18:41 UTC, oesukam commented on src/__tests__/__utils__/helperFunctions.test.js
> +    });
Empty line required.

2019-04-29 18:41 UTC, oesukam commented on src/__tests__/__views__/ReadArticle.test.js
> +  });
Empty line required.

2019-04-29 18:41 UTC, oesukam commented on src/__tests__/__views__/ReadArticle.test.js
> +  });
Empty line required.

2019-04-29 18:41 UTC, oesukam commented on src/__tests__/__views__/ReadArticle.test.js
> +  });
Empty line required.

2019-04-29 18:41 UTC, oesukam commented on src/__tests__/__views__/ReadArticle.test.js
> +  });
Empty line required.

2019-04-29 18:41 UTC, oesukam commented on src/__tests__/__views__/ReadArticle.test.js
> +  });
Empty line required.

2019-04-29 18:41 UTC, oesukam commented on src/__tests__/__views__/ReadArticle.test.js
> +  });
Empty line required.

2019-04-29 18:41 UTC, oesukam commented on src/__tests__/__views__/ReadArticle.test.js
> +  });
Empty line required.

2019-04-29 18:41 UTC, oesukam commented on src/components/common/Cards/main.js
>  /* eslint global-require: "off" */
@YvesIraguha Should be disabled globally.

2019-04-29 18:41 UTC, oesukam commented on src/components/common/Cards/main.js
> +              src={image || require("../../../assets/img/author.svg")}
We should stick to es6 through out the project.

2019-04-29 18:41 UTC, oesukam commented on src/components/common/Cards/main.js
>                    src={require("../../../assets/img/thumb-down-outline.svg")}
You should use es6 with import

2019-04-30 10:55 UTC, oesukam requested changes

2019-04-30 10:55 UTC, oesukam commented on src/views/ReadArticle.js
> +  ...ownProps,
@YvesIraguha Why this? I think it is included by default.

2019-04-30 10:55 UTC, oesukam commented on src/views/ReadArticle.js
> +  constructor(props) {
@YvesIraguha They no longer use the constructor. Please check this article -> [React Constructor](https://hackernoon.com/the-constructor-is-dead-long-live-the-constructor-c10871bea599)

2019-04-30 10:55 UTC, oesukam commented on src/views/ReadArticle.js
> +    this.state = {
@YvesIraguha It should be initialized outside of the constructor.

2019-04-30 10:55 UTC, oesukam commented on src/views/ReadArticle.js
> +        <Navbar />
@YvesIraguha The navbar has to imported globally to avoid reputation.

2019-04-30 10:55 UTC, oesukam commented on src/views/ReadArticle.js
> +                    ? comments.map(comment => {
@YvesIraguha Extract this conditional rendering to make it an instance function

2019-04-30 10:55 UTC, oesukam commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
@YvesIraguha This file should be ignored

2019-04-30 12:11 UTC, oesukam requested changes

2019-04-30 12:11 UTC, oesukam commented on .gitignore
> +yarn.lock
@YvesIraguha Empty line at the end of the file required

2019-04-30 13:01 UTC, oesukam approved these changes

2019-04-30 13:01 UTC, merged