#165441605 Chore Current User
andela/titan-dev-ah-frontend pull request #44
Opened 2019-04-18 12:11 UTC by abayo-luc

#### What does this PR do?
Set current use to be accessible anywhere in the app
#### How should this be manually tested?
- clone the repo and check out the following branch `ft-set-current-user-165441605 `
- run `yarn start` and navigate to /sign_in in your browser
- And the current user will be accessible from the redux state - auth
### Related Pivotal tracker ID
#165441605

2019-04-23 10:03 UTC, espoirMur requested changes

2019-04-23 10:03 UTC, espoirMur commented on src/redux/actionTypes.js
> +export const PASSWORD_UPDATE_SUCCESS = "password_update_success";
@abayo-luc, May I know, Why action are in lower case here?

2019-04-24 09:31 UTC, niomwungeri-fabrice approved these changes
Good Job!

2019-04-24 12:48 UTC, espoirMur approved these changes

2019-04-25 11:16 UTC, puritybirir approved these changes

2019-04-25 11:16 UTC, merged