#163518663 Report Article
andela/titan-dev-ah-frontend pull request #46
Opened 2019-04-24 15:59 UTC by YvesIraguha

#### What does this PR do?
- Report article
#### Description of Task to be completed?
- Enable report article
#### How should this be manually tested?
- clone the repos and check out the branch `ft-report-article-163518663
- Run `yarn` to install all dependencies
- Run `yarn test` to run tests, they should all pass
- Start your backend server on the address `localhost:3000/`
- Create some articles using client tool like the postman 
- Grab slug of one of the articles you created. 
- Run `yarn start` to start your server
- Navigate to `localhost:8080/articles/slug/report`
- Report the article, you should see the response explaining whether the article was reported successfully or not. 
#### Any background context you want to provide?
- The html-css mockup of this story was not yet implemented. So, I designed the mockup and I will include it. 
#### What are the relevant pivotal tracker stories?
# 163518663 
#### Screenshots (if appropriate)
<img width="689" alt="Screen Shot 2019-04-24 at 17 58 44" src="https://user-images.githubusercontent.com/34691070/56674636-aafa6e80-66ba-11e9-9809-3d316ecd8ad4.png">

2019-04-25 08:50 UTC, espoirMur reviewed
This PR is outstanding @YvesIraguha! 
It has few files to review, the UI is awesome!
For a better user experience you should consider the following points: 
- Only authenticated users should be able to report an article. if a user is not authenticated we should prompt him to log in before reporting an article.
- Once a user has clicked to the submit button it should be disabled until the request is successful.
- Error message on report form validation should be in red

2019-04-25 08:58 UTC, espoirMur requested changes

2019-04-25 08:58 UTC, espoirMur commented on src/__tests__/__views__/ReportArticle.test.js
> +    const { wrapper } = shallowSetup();
This line is repeated in many places! Can you declare it as a global variable or in a before...

2019-04-25 08:58 UTC, espoirMur commented on src/redux/reducers/reportReducer.js
> +        ...state,
Can I know why you are returning both state and initial state here?
It looks like there is a duplication...

2019-04-25 08:58 UTC, espoirMur commented on src/views/ReportArticle.js
> +    const { description } = this.state;
can you please combine those 2 lines into one line? (Line 49 and 50)

2019-04-25 08:58 UTC, espoirMur commented on webpack.config.js
> +    publicPath: "/",
May I Know why we have this line?

2019-05-09 16:31 UTC, oesukam requested changes

2019-05-09 16:31 UTC, oesukam commented on src/__tests__/__actions__/reportArticleActions.test.js
> +  test("should return reporting and reported article actions", () => {
Empty line required

2019-05-09 16:31 UTC, oesukam commented on src/__tests__/__actions__/reportArticleActions.test.js
> +  test("should return reporting action type", () => {
Empty line required

2019-05-09 16:31 UTC, oesukam commented on src/__tests__/__actions__/reportArticleActions.test.js
> +  });
Empty line required

2019-05-09 16:31 UTC, oesukam commented on src/__tests__/__actions__/reportArticleActions.test.js
> +  test("should return reporting and error actions", () => {
Empty line required

2019-05-09 16:31 UTC, oesukam commented on src/__tests__/__reducers__/reportArticleReducer.test.js
> +  test("should return the reporting true", () => {
Empty line required

2019-05-09 16:31 UTC, oesukam commented on src/__tests__/__reducers__/reportArticleReducer.test.js
> +  test("should return the error response", () => {
Empty line required

2019-05-09 16:31 UTC, oesukam commented on src/__tests__/__reducers__/reportArticleReducer.test.js
> +  test("should return the response article reported", () => {
Empty line required

2019-05-09 16:31 UTC, oesukam commented on src/__tests__/__views__/ReportArticle.test.js
> +  test("should render the component for creating a report", () => {
Empty line required

2019-05-09 16:31 UTC, oesukam commented on src/__tests__/__views__/ReportArticle.test.js
> +  test("should respond on input change", () => {
Empty line required

2019-05-09 16:31 UTC, oesukam commented on src/__tests__/__views__/ReportArticle.test.js
> +  test("should submit a report", async () => {
Empty line required

2019-05-09 16:31 UTC, oesukam commented on src/__tests__/__views__/ReportArticle.test.js
> +  test("should handle report error", async () => {
Empty line required

2019-05-09 16:31 UTC, oesukam commented on src/__tests__/__views__/ReportArticle.test.js
> +  test("should try to submit a report without description", () => {
Empty line required

2019-05-09 16:31 UTC, oesukam commented on src/__tests__/__views__/ReportArticle.test.js
> +  test("should cancel report form", () => {
Empty line required

2019-05-09 16:31 UTC, oesukam commented on src/redux/reducers/reportReducer.js
> +export const reportArticle = (state = initialState, action) => {
Empty line required

2019-05-09 16:31 UTC, oesukam commented on src/redux/reducers/reportReducer.js
> +      return {
Don't need to spread as you are not updating anything

2019-05-10 05:38 UTC, oesukam approved these changes

2019-05-10 08:33 UTC, Musigwa-zz approved these changes

2019-05-10 09:03 UTC, espoirMur approved these changes

2019-05-10 09:03 UTC, espoirMur commented on src/__tests__/__actions__/reportArticleActions.test.js
> +  test("should return reporting and error actions", () => {
May I know why you are using **test** instead of **it**?

2019-05-10 09:21 UTC, merged