Ch setup routers 163518639
andela/titan-dev-ah-frontend pull request #49
Opened 2019-04-26 11:21 UTC by abayo-luc

### Why
Sets up navigation to link all the pages, and fixes navbar!

2019-04-26 11:44 UTC, espoirMur approved these changes

2019-04-29 08:24 UTC, espoirMur approved these changes
LGTM...
+1

2019-04-30 10:57 UTC, oesukam requested changes

2019-04-30 10:57 UTC, oesukam commented on src/components/common/AppBars/navBar.js
>  /* eslint global-require: "off" */
@abayo-luc Why this and not doing it globally?

2019-04-30 10:57 UTC, oesukam commented on src/components/common/AppBars/navBar.js
>                    src={require("../../../assets/img/quill-drawing-a-line.svg")}
@abayo-luc Let us keep with es6 by using `import` instead of `require`

2019-04-30 13:34 UTC, oesukam approved these changes

2019-04-30 13:34 UTC, merged