#165716231 Fix Reactions Buttons on Scroll
andela/titan-dev-ah-frontend pull request #52
Opened 2019-05-02 11:01 UTC by YvesIraguha

#### What does this PR do?
- Create styles for fixing reactions buttons on viewing article
#### Description of Task to be completed?
- Adjust styles of view article
- Add reporting form on view article
#### How should this be manually tested?
- Clone the repos and check out the branch `ch-fix-reactions-buttons-on-scroll-165716231`
- Run `yarn` command to install all dependencies
- Run `yarn test` to run all tests. You should see all the tests passing. 
- start your backend server and front-end server by `yarn start`
- Create articles in your backend. 
- Grab a slug of one article. 
- Open your browser and navigate to `/articles/:slug`. You should see the article. When you scroll down, reactions buttons should stay visible. When you click on more button, you should see the report article. When you click on the report article, the report article form should appear. When you click cancel on report article form, the reporting form should disappear. 

#### What are the relevant pivotal tracker stories?

#### Screenshots (if appropriate)
#### Questions:

2019-05-02 12:35 UTC, niomwungeri-fabrice approved these changes

2019-05-06 08:22 UTC, abayo-luc requested changes
Well done Mr. @YvesIraguha

2019-05-06 08:22 UTC, abayo-luc commented on src/components/reportingForm/ReportingForm.js
> +export const MoreReactions = props => {
you can separate these two components into different files.

2019-05-07 10:53 UTC, abayo-luc approved these changes

2019-05-07 12:51 UTC, oesukam requested changes

2019-05-07 12:51 UTC, oesukam commented on src/__tests__/__actions__/readArticleAction.test.js
> +const BASE_URL = process.env.API_URL;
@YvesIraguha Can't you destruct?

2019-05-07 12:51 UTC, oesukam commented on src/views/ReadArticle.js
> +    if (reportingForm === true) {
@YvesIraguha Change to `if(reportingForm)`

2019-05-07 12:51 UTC, oesukam commented on src/views/ReadArticle.js
>                        onClick={() => this.redirectToEdit()}
@YvesIraguha Should be called by reference

2019-05-08 07:32 UTC, oesukam approved these changes

2019-05-08 07:32 UTC, merged