#163518649 Comment on article
andela/titan-dev-ah-frontend pull request #56
Opened 2019-05-10 03:54 UTC by niomwungeri-fabrice

#### What does this PR do?
- Comment on article
#### Description of Task to be completed?
- Enable comment on an article
#### How should this be manually tested?
- clone the repos and check out the branch `ft-comment-on-article-163518649
- Run `yarn` to install all dependencies
- Run `yarn test` to run tests, they should all pass
- Start your backend server on the address `localhost:3000/`
- Create some articles using client tool like the postman 
- Grab slug of one of the articles you created. 
- Run `yarn start` to start your server
- Navigate to `localhost:8080/articles/:{slug}`
- Comment on an article you should see comment under the article.
#### Any background context you want to provide?
- None
#### What are the relevant pivotal tracker stories?
# 163518649

2019-05-13 10:18 UTC, abayo-luc approved these changes

2019-05-13 10:52 UTC, YvesIraguha requested changes
@niomwungeri-fabrice you did a great job. I can create a comment, read a comment, update a comment, and even delete a comment. Good job! For the user experience improvement, I have a couple of observations that I suggest can be improved. 
* First: 
<img width="815" alt="Screen Shot 2019-05-13 at 11 27 18" src="https://user-images.githubusercontent.com/34691070/57615247-8be55300-757b-11e9-81b6-73b340912a9e.png">Looking at the design of the comment view, I suggest that that bottom line which contains timestamp can be relocated to the top right corner of the comment container. The heart icon and those two buttons for edit and delete can be aligned to the bottom of the comment container. In addition, add a white space between comment's body and those icons. 

* Second, I signed out. After signing out, I come back to create a comment. The field allowed me to create a comment, but I didn't see any response: whether I have to login or not. I tried to inspect, and saw that I am trying to access a protected route. I would suggest that if a user is not logged in, when they try to click in the comment field, they should be redirected to login/signup route. 
* Third: When I am reading an article, I can switch to another article from the right side. However, when I try to click on the other article from the right side, comments for previous article stay. Comments of the article I am reading should the only comments to appear. 
* Fourth: I left comments regarding the codebase on respective lines of code. Check them. Let me know if I can collaborate with you for challenging parts.

2019-05-13 10:52 UTC, YvesIraguha commented on src/redux/actions/commentActions.js
> +      const { message, comment } = response.data;
@niomwungeri-fabrice I checked other files of the project before writing this review. In each other file, the format is `async/await` for promises can we stick to `async/await` instead of using `thenables`? Async/await has clean syntax and it helps in avoiding promise hell.

2019-05-13 10:52 UTC, YvesIraguha commented on src/redux/actions/commentActions.js
> +    .then(response => {
Check comment above.

2019-05-13 10:52 UTC, YvesIraguha commented on src/views/Comments.js
> +    ind: null
@niomwungeri-fabrice I am confused about the name of this variable. Is it `index` or `id`? I suggest that you make more descriptive of what it stands for.

2019-05-13 14:41 UTC, niomwungeri-fabrice commented on src/views/Comments.js
> +    ind: null
@YvesIraguha!

I have changed to index.

Thanks

2019-05-13 14:41 UTC, niomwungeri-fabrice commented on src/redux/actions/commentActions.js
> +      const { message, comment } = response.data;
@YvesIraguha 
I used promise because we hadn't agreed on those 2 possibilities before. But I have replaced `promises` with `async/await` as you suggested.
Thanks!

2019-05-13 15:16 UTC, niomwungeri-fabrice commented
> @niomwungeri-fabrice you did a great job. I can create a comment, read a comment, update a comment, and even delete a comment. Good job! For the user experience improvement, I have a couple of observations that I suggest can be improved.
> 
> * First:
>   <img alt="Screen Shot 2019-05-13 at 11 27 18" width="815" src="https://user-images.githubusercontent.com/34691070/57615247-8be55300-757b-11e9-81b6-73b340912a9e.png">Looking at the design of the comment view, I suggest that that bottom line which contains timestamp can be relocated to the top right corner of the comment container. The heart icon and those two buttons for edit and delete can be aligned to the bottom of the comment container. In addition, add a white space between comment's body and those icons.
> * Second, I signed out. After signing out, I come back to create a comment. The field allowed me to create a comment, but I didn't see any response: whether I have to login or not. I tried to inspect, and saw that I am trying to access a protected route. I would suggest that if a user is not logged in, when they try to click in the comment field, they should be redirected to login/signup route.
> * Third: When I am reading an article, I can switch to another article from the right side. However, when I try to click on the other article from the right side, comments for previous article stay. Comments of the article I am reading should the only comments to appear.
> * Fourth: I left comments regarding the codebase on respective lines of code. Check them. Let me know if I can collaborate with you for challenging parts.

Hi, Mr. @YvesIraguha!

>* Here's the new design with suggested changes `on posted time`
<img width="831" alt="Screen Shot 2019-05-13 at 17 09 20" src="https://user-images.githubusercontent.com/25322304/57632474-088b2800-75a2-11e9-95a7-bd5fab2300e2.png">

>* Second Point; I have I explained this to my demo video which will be shared later on. I said that I am waiting for @espoirMur PR about High order Component to be ready so that we can use his implementation about protected routes.

>* Third and Fourth Points have been resolved you can pull changes and check again.

Thanks!

2019-05-14 07:46 UTC, YvesIraguha approved these changes

2019-05-14 07:48 UTC, YvesIraguha reviewed
Well done @niomwungeri-fabrice. However, consider fixing what happens when a user is logged out, after the chore of HOC is merged.

2019-05-14 07:58 UTC, niomwungeri-fabrice commented
> Well done @niomwungeri-fabrice. However, consider fixing what happens when a user is logged out, after the chore of HOC is merged.

Got It! Thanks

2019-05-16 08:14 UTC, abayo-luc requested changes

2019-05-16 08:14 UTC, abayo-luc commented on src/views/Comments.js
> +import authorImage from "../assets/img/user.jpg";
can you use no-image `no-thumbnail.png` as an indicator that there is no user-avatar?

2019-05-16 08:14 UTC, abayo-luc commented on src/views/Comments.js
> +import authorImage from "../assets/img/user.jpg";
or use `user.png` as default user-avatar.

2019-05-16 08:25 UTC, oesukam requested changes

2019-05-16 08:25 UTC, oesukam commented on src/redux/actions/commentActions.js
> +});
New line

2019-05-16 08:25 UTC, oesukam commented on src/redux/actions/commentActions.js
> +});
New line

2019-05-16 08:25 UTC, oesukam commented on src/views/Comments.js
> +    return Object.values(comments).length
You can use `Object.values` without checking for the `length`

2019-05-16 08:25 UTC, abayo-luc approved these changes

2019-05-16 10:48 UTC, oesukam approved these changes

2019-05-16 10:48 UTC, merged