163518666 Liking a comment
andela/titan-dev-ah-frontend pull request #60
Opened 2019-05-16 11:33 UTC by niomwungeri-fabrice

#### What does this PR do?
- Comment on article
#### Description of Task to be completed?
- Enable comment on an article
#### How should this be manually tested?
- clone the repos and check out the branch `ft-liking-a-comment-163518666`
- clone the repos and check out the branch `bg-fix-comments-165964990`
- Run `yarn` to install all dependencies on both branches
- Run `yarn test` to run tests, they should all pass on both branch
- Start your backend server on the address `localhost:3000/` by issuing `yarn start` command
- Create some articles using client tool like the postman 
- Grab slug of one of the articles you created. 
- Run `yarn start` to start your server
- Navigate to `localhost:8080/articles/:{slug}`
- Like on a comment you should see the color of the heart icon change under the article.
#### Any background context you want to provide?
- None
#### What are the relevant pivotal tracker stories?
# 163518649

2019-05-16 18:26 UTC, espoirMur reviewed
Looks great!

2019-05-17 09:21 UTC, abayo-luc approved these changes

2019-05-17 09:32 UTC, espoirMur approved these changes

2019-05-17 09:36 UTC, oesukam requested changes

2019-05-17 09:36 UTC, oesukam commented on src/__tests__/__actions__/commentsActions.test.js
>      });
New line

2019-05-17 09:36 UTC, oesukam commented on src/__tests__/__reducers__/commentsReducer.test.js
> +  });
New line

2019-05-17 09:36 UTC, oesukam commented on src/__tests__/__reducers__/commentsReducer.test.js
>    });
New line

2019-05-17 09:36 UTC, oesukam commented on src/__tests__/__reducers__/commentsReducer.test.js
> +  });
New line

2019-05-17 09:36 UTC, oesukam commented on src/__tests__/__reducers__/commentsReducer.test.js
> +  });
New line

2019-05-17 09:36 UTC, oesukam commented on src/__tests__/__reducers__/commentsReducer.test.js
> +  });
New line

2019-05-17 09:36 UTC, oesukam commented on src/__tests__/__views__/Comments.test.js
> +    });
New line

2019-05-17 09:53 UTC, oesukam approved these changes

2019-05-17 09:53 UTC, merged