#165969658 Fix Navigation Bar Picture
andela/titan-dev-ah-frontend pull request #63
Opened 2019-05-16 16:38 UTC by YvesIraguha

#### What does this PR do?
- Display correct image in navigation bar
#### Description of Task to be completed?
- Create the component for picture in navigation bar
- Create appropriate tests 
#### How should this be manually tested?
- Clone the repository and checkout the branch `ft-nav-bar-picture-165969658`
- Start the backend and front-end server 
- If you are logged in you should see the profile picture, username, or first name and last name in the navigation bar
- If you are not logged in, you should see the default profile picture only. 

#### What are the relevant pivotal tracker stories?
# 165969658

2019-05-16 16:43 UTC, abayo-luc approved these changes

2019-05-17 07:18 UTC, niomwungeri-fabrice approved these changes

2019-05-17 07:29 UTC, oesukam requested changes

2019-05-17 07:29 UTC, oesukam commented on src/components/common/AppBars/ProfilePicture.js
> +};
Empty line

2019-05-17 07:39 UTC, oesukam approved these changes

2019-05-17 07:39 UTC, merged