164364254 Search Results Page
andela/titan-dev-ah-frontend pull request #7
Opened 2019-03-08 10:58 UTC by abayo-luc

#### What does this PR do?
Add search results page
#### Description of Task to be completed?
• create a card for an article as well as user
• Search query input field
• Side component for relevant author and tas
#### How should this be manually tested?
* Fetch origin
* Checkout the branch `ft-search-results-page-164364254 `
* Open ```./pages/search-results.html#articles```
* and use the inspector to view the page with different devices.
#### What are the relevant pivotal tracker stories?
164364254
### Screenshots
<img width="1440" alt="screen shot 2019-03-08 at 12 56 22" src="https://user-images.githubusercontent.com/20681465/54024972-d32d1d00-41a1-11e9-937c-c860e2f0b5b1.png">
<img width="1440" alt="screen shot 2019-03-08 at 12 56 33" src="https://user-images.githubusercontent.com/20681465/54024973-d32d1d00-41a1-11e9-97b9-e376039fa25f.png">
<img width="813" alt="screen shot 2019-03-08 at 12 57 08" src="https://user-images.githubusercontent.com/20681465/54024974-d32d1d00-41a1-11e9-9018-8d7d634017c9.png">
<img width="813" alt="screen shot 2019-03-08 at 12 57 21" src="https://user-images.githubusercontent.com/20681465/54024975-d32d1d00-41a1-11e9-943b-3d0e0412e33c.png">
<img width="813" alt="screen shot 2019-03-08 at 12 57 29" src="https://user-images.githubusercontent.com/20681465/54024976-d3c5b380-41a1-11e9-95cc-bb8dc870348e.png">

2019-03-11 12:25 UTC, YvesIraguha approved these changes
@abayo-luc The page is responsive, and it meets specifications on the design.

2019-03-11 12:33 UTC, YvesIraguha commented on css/main.css
> +  flex-direction: row;
There is a mixin defined for these two properties ` display: flex;
  flex-direction: row;`. I think for consistency you can use it `@include raw`

2019-03-12 08:10 UTC, espoirMur commented
Sorry for this late review bro!!
It looks nice, 
What do you think about the space between author avatar and the article main picture here on mobile view?
<img width="386" alt="Screen Shot 2019-03-12 at 10 07 07" src="https://user-images.githubusercontent.com/18573157/54184291-f3fdb700-44ae-11e9-8ae5-764e2d4cee59.png">

2019-03-12 08:16 UTC, espoirMur requested changes

2019-03-12 08:16 UTC, espoirMur commented on pages/search-results.html
> +                    style="width: 100px; height: 100px; border-radius: 50%"
Can you please put the style in the sass file for consistency?

2019-03-12 14:50 UTC, espoirMur approved these changes

2019-03-14 07:00 UTC, puritybirir approved these changes

2019-03-14 07:00 UTC, merged